insert into pools (name, reason, secondary) values ('main', '', 'secondary,other');
insert into pools (name, reason) values ('secondary', '');
insert into pools (name, reason) values ('other', '');
insert into machines (name, machine, status, reason) values ('main', 'main1', '', '');
insert into machines (name, machine, status, reason) values ('main', 'main2', '', '');
insert into machines (name, machine, status, reason) values ('main', 'main3', '', '');
insert into machines (name, machine, status, reason) values ('secondary', 'secondary1', '', '');
insert into machines (name, machine, status, reason) values ('secondary', 'secondary2', '', '');
insert into machines (name, machine, status, reason) values ('secondary', 'secondary3', '', '');
insert into machines (name, machine, status, reason) values ('other', 'other1', '', '');
insert into machines (name, machine, status, reason) values ('other', 'other2', '', '');
insert into machines (name, machine, status, reason) values ('other', 'other3', '', '');
