# vim: ft=dockerfile
FROM ubuntu

ENV TZ=Europe/Minsk
ENV TERM=xterm
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN DEBIAN_FRONTEND="noninteractive"
RUN apt-get -y update && apt-get -y install \
    python python-dev build-essential \
    alien \
    python-wxgtk3.0

RUN pip install PyInstaller
